services:
  backend:
    build:
      context: ./Backend
      args:
        VERSION: ${WAVENODE_VERSION:-0.1.5}

  frontend:
    build:
      context: ./Frontend
      args:
        VERSION: ${WAVENODE_VERSION:-0.1.5}

  updater:
    build:
      context: ./Updater
